name: drone_audio
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - flask
  - pip
  - pip:
    - transformers
